export const PUBLIC_FEEDBACK_ERROR_CODES = {
  PORTAL_UNAVAILABLE: "PUBLIC_FEEDBACK_PORTAL_UNAVAILABLE",
  NO_ACTIVE_BRANCHES: "PUBLIC_FEEDBACK_NO_ACTIVE_BRANCHES",
  IDEMPOTENCY_KEY_REQUIRED: "PUBLIC_FEEDBACK_IDEMPOTENCY_KEY_REQUIRED",
  IDEMPOTENCY_KEY_INVALID: "PUBLIC_FEEDBACK_IDEMPOTENCY_KEY_INVALID",
  VALIDATION_FAILED: "PUBLIC_FEEDBACK_VALIDATION_FAILED",
  ACCESS_DENIED: "PUBLIC_FEEDBACK_ACCESS_DENIED",
  HONEYPOT_REJECTED: "PUBLIC_FEEDBACK_REJECTED"
} as const;

export const QR_FEEDBACK_ERROR_CODES = {
  QR_UNAVAILABLE: "QR_FEEDBACK_LINK_UNAVAILABLE",
  QR_NOT_FOUND: "QR_FEEDBACK_CODE_NOT_FOUND",
  QR_CREATION_UNAVAILABLE: "QR_FEEDBACK_CREATION_UNAVAILABLE",
  QR_ACCESS_DENIED: "QR_FEEDBACK_ACCESS_DENIED",
  QR_BRANCH_REQUIRED: "QR_FEEDBACK_BRANCH_REQUIRED",
  QR_BRANCH_LOCKED: "QR_FEEDBACK_BRANCH_LOCKED",
  QR_NAME_REQUIRED: "QR_FEEDBACK_NAME_REQUIRED",
  QR_IDEMPOTENCY_KEY_REQUIRED: "QR_FEEDBACK_IDEMPOTENCY_KEY_REQUIRED",
  QR_IDEMPOTENCY_KEY_INVALID: "QR_FEEDBACK_IDEMPOTENCY_KEY_INVALID",
  QR_VALIDATION_FAILED: "QR_FEEDBACK_VALIDATION_FAILED",
  QR_TOKEN_GENERATION_FAILED: "QR_FEEDBACK_TOKEN_GENERATION_FAILED",
  QR_HONEYPOT_REJECTED: "QR_FEEDBACK_REJECTED"
} as const;
