export const FEEDBACK_WORKFLOW_ERRORS = {
  STATUS_INVALID: "FEEDBACK_STATUS_INVALID",
  TRANSITION_INVALID: "FEEDBACK_STATUS_TRANSITION_INVALID",
  NOTE_INVALID: "FEEDBACK_NOTE_INVALID",
  ACTIVITY_NOT_FOUND: "FEEDBACK_ACTIVITY_NOT_FOUND",
  ACCESS_DENIED: "FEEDBACK_WORKFLOW_ACCESS_DENIED",
  // Phase 10 assignment errors
  ASSIGNMENT_INVALID: "FEEDBACK_ASSIGNMENT_INVALID",
  ASSIGNMENT_FORBIDDEN: "FEEDBACK_ASSIGNMENT_FORBIDDEN",
  ASSIGNEE_NOT_FOUND: "FEEDBACK_ASSIGNEE_NOT_FOUND",
  ASSIGNEE_INACTIVE: "FEEDBACK_ASSIGNEE_INACTIVE",
  ASSIGNEE_BRANCH_FORBIDDEN: "FEEDBACK_ASSIGNEE_BRANCH_FORBIDDEN",
  ASSIGNMENT_CONFLICT: "FEEDBACK_ASSIGNMENT_CONFLICT",
  // Phase 10 category errors
  CATEGORY_INVALID: "FEEDBACK_CATEGORY_INVALID",
  CATEGORY_NOT_FOUND: "FEEDBACK_CATEGORY_NOT_FOUND",
  CATEGORY_INACTIVE: "FEEDBACK_CATEGORY_INACTIVE",
  CATEGORY_CONFLICT: "FEEDBACK_CATEGORY_CONFLICT",
  // Phase 10 priority errors
  PRIORITY_INVALID: "FEEDBACK_PRIORITY_INVALID",
  PRIORITY_CONFLICT: "FEEDBACK_PRIORITY_CONFLICT"
} as const;
