export const FEEDBACK_CATEGORY_ERRORS = {
  NOT_FOUND: "FEEDBACK_CATEGORY_NOT_FOUND",
  NAME_CONFLICT: "FEEDBACK_CATEGORY_NAME_CONFLICT",
  INACTIVE: "FEEDBACK_CATEGORY_INACTIVE",
  INVALID: "FEEDBACK_CATEGORY_INVALID",
  CONFLICT: "FEEDBACK_CATEGORY_CONFLICT"
} as const;
