export const MANUAL_FEEDBACK_ERROR_CODES = {
  IDEMPOTENCY_KEY_REQUIRED: "MANUAL_FEEDBACK_IDEMPOTENCY_KEY_REQUIRED",
  IDEMPOTENCY_KEY_INVALID: "MANUAL_FEEDBACK_IDEMPOTENCY_KEY_INVALID",
  SOURCE_INVALID: "MANUAL_FEEDBACK_SOURCE_INVALID",
  ACCESS_DENIED: "MANUAL_FEEDBACK_ACCESS_DENIED"
} as const;

export type ManualFeedbackErrorCode =
  (typeof MANUAL_FEEDBACK_ERROR_CODES)[keyof typeof MANUAL_FEEDBACK_ERROR_CODES];
